app.api.key=secure-key-andrei

# Numele aplicatiei
spring.application.name=SiemProject

# Configurare Baza de Date H2 (Modul Oracle)
spring.datasource.url=jdbc:h2:file:./data/siemdb;MODE=Oracle
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 (ca sa vezi tabelele in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate (creaza automat tabelele pentru tine)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true